version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:5000"
        volumes:
            - .:/code
        links:
            - db
        networks:
            - default
        depends_on:
            - "db"
      
    redis:
        image: "redis:alpine"
        
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "test"
        volumes:
            - ./docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
      
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
    db:
        image: mysql:5.7.13
        ports: 
            - "8001:8001"
        environment:
            MYSQL_DATABASE: MyDataBase
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default

    adminer:
        image: adminer
        ports:
            - 8080:8080
    
volumes:
    persistent: